v2.8 (5 Jul 2013)

diff --git a/src/tools/mkexternalsh b/src/tools/mkexternalsh
--- a/src/tools/mkexternalsh
+++ b/src/tools/mkexternalsh
@@ -3,7 +3,7 @@
 # the latter is included by all LoopTools code, with the purpose
 # of making internal symbols "invisible" from the outside
 # this file is part of LoopTools
-# last modified 15 Jul 11 th
+# last modified 11 Sep 12 th
 
 
 base=`dirname $0`/../..
@@ -26,11 +26,12 @@ set -- `nm $lib | awk '
   }
   $2 ~ /^(T|C)$/ && $3 !~ /^_*(\
 a00c|a00|a00subc|a00sub|a0c|a0|a0subc|a0sub|\
-b001c|b001|b00c|b00|b0c|b0ic|b0i|b0|b111c|b111|b11c|b11|b1c|b1|bgetc|bget|\
+b001c|b001|b00c|b00|b0c|b0ic|b0i|b0|b111c|b111|b11c|b11|b1c|b1|\
+bgetc|bget|bputc|bput|\
 db00c|db00|db0c|db0|db11c|db11|db1c|db1|\
-c0c|c0ic|c0i|c0|c0subc|c0sub|cgetc|cget|\
-d0c|d0ic|d0i|d0|d0subc|d0sub|dgetc|dget|\
-e0c|e0ic|e0i|e0|e0subc|e0sub|egetc|eget|\
+c0c|c0ic|c0i|c0|c0subc|c0sub|cgetc|cget|cputc|cput|\
+d0c|d0ic|d0i|d0|d0subc|d0sub|dgetc|dget|dputc|dput|\
+e0c|e0ic|e0i|e0|e0subc|e0sub|egetc|eget|eputc|eput|\
 li2c|li2csub|li2|li2sub|li2omxc|li2omxcsub|li2omx|li2omxsub|\
 ltini|ltexi|ltcache|ltvars|ltregul|\
 clearcache|markcache|restorecache|getcachelast|setcachelast|\
@@ -49,30 +50,34 @@ fdefs=""
 cdefs=""
 c_defs=""
 
-[ -f $ext ] && mv -f $ext $ext.old
+test -f $ext && mv -f $ext $ext.old
 touch $ext
-[ -f $cext ] && mv -f $cext $cext.old
+test -f $cext && mv -f $cext $cext.old
 touch $cext
 
 cd build
 
-while [ $# -gt 1 ] ; do
+while test $# -gt 1 ; do
   file=
   cppflags=
   for file in $1.[Fc] ; do
     break
   done
-  [ -z "$file" ] && case "$1" in
+  test -z "$file" && case "$1" in
   *C)	file=`echo "$1.F" | sed 's/C\.F$/\.F/'`
 	cppflags="-DCOMPLEXPARA"
 	;;
   esac
   case $file in
   *.c)	sym=`gcc -E -P $file | sed -n "
-	  s|^[^ ]* *\($2\)(.*|\1|pI
-	  s|} \($2\);|\1|pI
+	  s|^[^ ]* *\($2\)_*(.*|\1|pI
+	  s|} \($2\)_*;|\1|pI
 	  T
 	  q"`
+	test ${sym}x = x && {
+	  echo "$0 bug for file $file sym $2"
+	  exit 1
+	}
 	c_defs="$c_defs
 #define ${sym}_ $prefix${sym}_"
 	cdefs="$cdefs
@@ -89,12 +94,16 @@ while [ $# -gt 1 ] ; do
 	  s|^[^c*].*common */\($sym\).*|\1|pI
 	  T
 	  q"`
+	test ${sym}x = x && {
+	  echo "$0 bug for file $file sym $2"
+	  exit 1
+	}
 	fdefs="$fdefs
 #define $sym $prefix$sym"
 	;;
   esac
   echo $sym
-  [ -z "$sym" ] && echo "Symbol $2 not found in $file." 1>&2
+  test -z "$sym" && echo "Symbol $2 not found in $file." 1>&2
   shift 2
 done
 
